#!/usr/bin/env python3
"""
Outlook App Password Creation Guide
This script provides step-by-step instructions for creating Outlook App Passwords.
"""

def show_outlook_guide():
    print("=" * 70)
    print("📧 Outlook App Password Creation Guide")
    print("=" * 70)
    
    print("\n🔍 If you can't find 'Advanced security options', try these steps:")
    print("\n1️⃣ METHOD 1 - Direct Security Page:")
    print("   • Go to: https://account.microsoft.com/security")
    print("   • Sign in with: noblequest.edu@outlook.com")
    print("   • Look for 'Security' tab or 'Sign-in security'")
    print("   • Find 'Advanced security options' or 'App passwords'")
    
    print("\n2️⃣ METHOD 2 - Alternative Path:")
    print("   • Go to: https://myaccount.microsoft.com/")
    print("   • Click 'Security' in the left menu")
    print("   • Look for 'Advanced security options'")
    print("   • Find 'App passwords' section")
    
    print("\n3️⃣ METHOD 3 - If App Passwords are Hidden:")
    print("   • First enable 'Two-step verification'")
    print("   • Go to: https://account.microsoft.com/security")
    print("   • Click 'Advanced security options'")
    print("   • Enable 'Two-step verification' if not already enabled")
    print("   • Then 'App passwords' should appear")
    
    print("\n4️⃣ METHOD 4 - Direct App Password Link:")
    print("   • Try: https://account.microsoft.com/security/app-passwords")
    print("   • Or: https://myaccount.microsoft.com/security/app-passwords")
    
    print("\n📝 App Password Requirements:")
    print("   • Must be exactly 16 characters")
    print("   • No spaces or dashes")
    print("   • Example format: abcdefghijklmnop")
    print("   • Generated by Microsoft (you don't create it)")
    
    print("\n⚠️ Common Issues:")
    print("   • App Passwords only work with 2FA enabled")
    print("   • Some accounts may not have App Password option")
    print("   • Corporate/Work accounts may have restrictions")
    
    print("\n🔄 Alternative Solutions:")
    print("   1. Use Gmail instead (easier setup)")
    print("   2. Use Yahoo instead (easier setup)")
    print("   3. Contact Microsoft support")
    
    print("\n" + "=" * 70)

def test_current_password():
    print("\n🧪 Testing Current App Password...")
    print("Current password: cehmjputdyfikvzc")
    print("Length:", len("cehmjputdyfikvzc"))
    
    if len("cehmjputdyfikvzc") != 16:
        print("❌ Password length is incorrect (should be 16 characters)")
        return False
    
    if " " in "cehmjputdyfikvzc" or "-" in "cehmjputdyfikvzc":
        print("❌ Password contains spaces or dashes (not allowed)")
        return False
    
    print("✅ Password format looks correct")
    return True

def main():
    show_outlook_guide()
    test_current_password()
    
    print("\n💡 Next Steps:")
    print("1. Try creating a new App Password following the guide above")
    print("2. If still having issues, consider switching to Gmail")
    print("3. Run: python quick_email_fix.py (option 2 for Gmail)")
    
    print("\n" + "=" * 70)

if __name__ == "__main__":
    main()
